apiVersion: v1
kind: Service
metadata:
  name: weatherapp-auth
  namespace: authentication
spec:
  selector:
    app.kubernetes.io/name: weatherapp-auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-auth
  namespace: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: weatherapp-auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weatherapp-auth
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: weatherapp-auth
          image: mostafagheta/weather-auth:393264fc4b1cac7e182526f582222e8ff87043bf
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql.authentication.svc.cluster.local
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: auth-password
            - name: DB_NAME
              value: weatherapp
            - name: DB_PORT
              value: "3306"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: secret-key
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
