apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
  namespace: authentication
spec:
  template:
    spec:
      containers:
        - name: mysql-init
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: auth-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: auth-password
            - name: MYSQL_HOST
              value: "mysql.authentication.svc.cluster.local"
            - name: MYSQL_PORT
              value: "3306"
          command: ["/bin/sh", "-c"]
          args:
            - |
              mysql -h${MYSQL_HOST} -P${MYSQL_PORT} -uroot -p${MYSQL_ROOT_PASSWORD} <<EOF
              CREATE DATABASE IF NOT EXISTS weatherapp;
              CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
              GRANT ALL PRIVILEGES ON weatherapp.* TO '${MYSQL_USER}'@'%';
              FLUSH PRIVILEGES;
              EOF
      restartPolicy: OnFailure
  backoffLimit: 4
