apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: authentication
type: Opaque
data:
  root-password: YWRtaW4=
  auth-user: YWRtaW4=
  auth-password: YWRtaW4=
  secret-key: c3VwZXJzZWNyZXRrZXk=
