apiVersion: v1
kind: Service
metadata:
  name: weatherapp-weather
  namespace: weather
spec:
  selector:
    app: weather
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-weather
  namespace: weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: weatherapp-weather
          image: mostafagheta/weather-weather:393264fc4b1cac7e182526f582222e8ff87043bf
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
            - containerPort: 5000
          env:
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: weather
                  key: apikey
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
