apiVersion: v1
kind: Secret
metadata:
  name: ui-secret
  namespace: ui
type: Opaque
data:
  # Base64 for 'supersecretkey' - must match the one in authentication namespace
  secret-key: c3VwZXJzZWNyZXRrZXk=
